language: minimal
sudo: required
services:
  - docker

env:
  - GHC_VER: head
  - GHC_VER: 8.6.2
  - GHC_VER: 8.4.4
  - GHC_VER: 8.2.2
  - GHC_VER: 8.0.2
  - GHC_VER: 7.10.3
  - GHC_VER: 7.8.4

matrix:
  allow_failure: head

install:
  - docker --version

script:
  - docker build . -f Dockerfile --build-arg GHC_VER=${GHC_VER} --tag migamake/haskell-build:${GHC_VER} || exit 1;

deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push migamake/haskell-build:${GHC_VER};
